name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: |
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=amd64
          go build -o main ./main.go
          tar czf main.tar.gz main

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: main.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: main

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to server
        env:
          SERVER_IP: 38.147.171.230
          USERNAME: root
          SSH_PRIVATE_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHivBcH5PJWSqumJm8F/tpciOPPFxGfw53B8ztHEe/S0O+hogh5NDrbVpx/llwLlI79bQv78ekhvYtTyY6mUW+gcZMj63i3nEARqQ3P9KDEi6AwjAimJQDPiIBQcNt/paU/AC98FaF2QbaPBa7j9orts/fp8KqSnkYwSn2Z+ESKuMy7vNqGQztvXODrv1SVzwTHzvsYQIuDROzlTjpkOp4ZUdZ6SLpaG8SJis4uCR4Qy48on/d4bty/3fnbElpbot4WRAH05ON7TYlqVJh2UiTXoTc1MZXJdasyr2pN2UTOTfucRd3DCRfFfSFwAIVfOhLEH5AYxfDiJVWOWzYlZ4ZwmuS48oaakBNQZBuR1Xu2djz2bJmdQq/PIUWmDh7JLq1tUCoRYTduWIDZDPpeSxeA34wcTxkngQzyjozQarruOxcSuy9DhWDaaS3KdWcEzkxBfZDfDLqC7HOX27xImgEFh3F6nQdFUKMZ9E7vCCOMqu5LWrn80a8iQlFZKH+ESwChqV5/sVGTlaKMDULZnPB7gsheX7Xw2cn6e3lrU6PHdYvZgXvgrE44f56QMOPp5TxNDeq8dCzdinSqppQjhe9gmXhVHymIKKvugajR+ZoMRUG6R0AxtgyHs8m0WhMMaExCxcrWQujEkptvQKtbcJwhEkUVBWQJpgQpR8FFFSJaw== admin@DESKTOP-NMEKPFK
        run: |
          echo "Server IP: $SERVER_IP"
          echo "Username: $USERNAME"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp main.tar.gz $USERNAME@$SERVER_IP:/tmp
          ssh $USERNAME@$SERVER_IP 'bash -s' <<-'EOF'
            cd /home/
            if [ -f main.bak ]; then
              rm main.bak
            fi
            if [ -f main ]; then
              mv main main.bak
            fi
            tar xzf /tmp/main.tar.gz -C /home/
            chmod +x /home/main
            ./main
          EOF
